services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: admin
      PMA_PASSWORD: admin
      PMA_DB: mydb