spring.application.name=cabot
# Si tu MySQL está en Docker con el puerto 3306 mapeado al host
spring.datasource.url=jdbc:mysql://localhost:3306/mydb
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Opcional: Ayuda a ver qué hace Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
